export function generateHeader(): string {
  return `<h1 align="center">Hi <img src="public/webp/peepoHey.webp" alt="Hi" width="30" height="30" />, I'm Dobromir Kirov (Bodrie)</h1>
<h3 align="center">A passionate software developer from Bulgaria</h3>
<p align="center">This page is auto generated by the repo itself</p>

<p align="center">
The repository serves as a centralized, automated archive of my work across various GitHub identities.
Due to professional requirements, a significant portion of my technical output has been generated under enterprise and secondary accounts. To provide a comprehensive view of my journey as a developer, this page pulls together several metrics into my personal account.
</p>

<a href="https://Bodrie.github.io/Bodrie/" target="_blank">
Check out the auto generated github pages as well
</a>`;
}
